### PR TITLE
Add badges to README

### PR DESCRIPTION
**Pull request by jmcanterafonseca**

### CODE REVIEW

**Comment by jmcanterafonseca** [comment]
@albertinisg r?

**Comment by albertinisg** [comment]
How about including the Docker badge? As it stands in the [project badges page](https://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/Project_Badges).

[Docker badge](https://hub.docker.com/r/fiware/tutorials.tourguide-app/)

**Comment by albertinisg** [comment]
@jmcanterafonseca please address my comment

**Comment by jmcanterafonseca** [comment]
done

**Comment by albertinisg** [comment]
LGTM. Thanks!

**Pull request merged**
