### PR TITLE
Use official pep-wilma docker image with custom entrypoint.

### PR DESCRIPTION
**Pull request by dmabtrg**
This replaces PR #53, as this should be done against `develop` branch and not `master`.

### CODE REVIEW

**Comment by jmcanterafonseca** [comment]
I cannot understand what these scripts are doing ... ?? please could you explain and add comments accordingly?

**Comment by dmabtrg** [comment]
The official docker image for pep-wilma requires that the user provides the configuration file by using a volume from the host, while the image from Bitergia currently used generates the configuration file from the provided environment variables, doing some extra checks before starting the service.  With the custom entrypoint script, our goal is to keep those extra checks and configuration generation while using the official docker image.  The entrypoint script does the following steps:
- Installs curl in the container, as we need it for some checks and the official image does not have it installed by default.
- Checks the authzforce version to be able to configure the right path for the authzforce urls.
- Checks the variables needed to generate the configuration file and sets default values when not defined.
- Waits for idm to create the domain in authzforce.
- Gets the domain from authzforce, as we need to add this to the configuration file.
- Waits for idm to finish the provision.
- Updates the domain permissions for the pepproxy user on keystone.
- As the current image does not support versioned tags, we add an extra step to checkout the release tag that we want.  There is an open issue to address this (ging/fiware-pep-proxy#14).
- Generates the configuration file from a template, using the values from the environment variables.
- The official image starts the pep proxy via 'node server.js' as root.  Though this works, if the process throws an error, the process stops and the container will stop, bringing down other containers that depend on this one.  To avoid this, we used the 'forever' command to keep the server running and respawn the process if it stops.  As the forever command will spawn the process in the background, we just tail the logs to keep the container running. Also, we start the process as a regular user instead of using root.

The use of a new tourguide-config container is to try and avoid the use of host volumes and use volumes from another container, as this does not work when using docker-machine/docker-swarm.  Also, if we try to provide this volume from the tourguide container, docker will refuse due to circular links between containers (tourguide links to pep-wilma, so we can't link pep-wilma to tourguide).

The auth-token.sh script is a helper script to retrieve a valid x-auth-token for a user (i.e. to use it with curl).  We can maybe move this script to tourguide, as it does not depend on the pep proxy.

**Comment by jmcanterafonseca** [comment]
I would suggest to keep docker housekeeping stuff as simple as possible. If the official docker image has flaws let's report them to their owners. 

The operations to wait for IDM, etc, couldn't they be done manually by invoking a provisioning script, separate from docker? It will help out a lot, as users will be able to know what is really needed to make it work together PEP and IDM. 

Magic inside docker scripts does not help in terms of teaching, what is the final purpose of the application ...

**Comment by jmcanterafonseca** [comment]
any update on this?

**Comment by dmabtrg** [comment]
It seems that Authzforce 4.4.x has some changes from version 4.2.0 and is not yet supported by idm nor pep-wilma (see ging/fiware-idm#62 and ging/fiware-pep-proxy#17).  It seems it will be supported in the next release.  This change, both in idm and pep-wilma, should allow us to use the pep-wilma image by just providing the configuration file and avoiding the custom docker-entrypoint.sh

I think we can close this PR and wait for the new release to be available.

**Comment by dmabtrg** [comment]
We're waiting for the new pep-wilma 5.3.1 official docker image, so this is not needed anymore.

I'm closing it.

**Pull request closed without merging**
