### PR TITLE
Use official pep-wilma docker image.

### PR DESCRIPTION
**Pull request by dmabtrg**
This allows us to use the official pep-wilma docker image while keeping the modifications done on [Bitergia's pep-wilma image](https://hub.docker.com/r/bitergia/pep-wilma/).  This is another step in fixing #43.

### CODE REVIEW

**Comment by albertinisg** [comment]
LGTM. @jmcanterafonseca, would you like to have a look?

**Comment by dmabtrg** [comment]
I just realized that this could break compatibility with docker swarm/machine (i.e. creating a tourguide instance on Fiware Cloud), due to the use of volumes from the host.  I need to test it before this can be merged.

**Comment by jmcanterafonseca** [comment]
guys,

if we need to report something to the author of the docker image, please let us know.

**Comment by dmabtrg** [comment]
The problem here is that we added some extra checks and preconfiguration steps on our custom images, so I'm trying to use our custom docker-entrypoint with the official image to keep those changes.  To do this, I've used host volumes to mount the required files on the official image, but this approach has some problems when using docker machine/swarm, so I'm trying something else using volumes from a data container.

**Comment by dmabtrg** [comment]
This PR should be done against `develop` and not `master`.  I've opened #66 to replace this PR and closing this one.

**Pull request closed without merging**
